sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: sQuiVF5AiNLiYcp4U0trj+F8yqySCu3MWWd8cuOBCNkNF5D9mXPYhltDT7gZ8hGwzGhKUkRy5msf2YPpRsvzh4TADKSUn8q++gzuoVCEUVLBQn6qVyQndkMJWIWr0SpWcKkxqOERT11Kuplw9vK9qHUlbxLApB0qmhIIX8qA9r8Kk2IBWh3/20VEK1pYWxMx+GUXA5uVo3NfDpOgAJkQYymvdmpjSp4UK56n9Sw3VdzGs2pvtR1w/WNBOIIPocgqVJJcAXbPXUpdgK6hjYk+rV5ociTfft+tQ7IzqF6WaavR9pJIhgQPkNtFk616+UxSLzCwLYHuyyAd8OyK1h6KDAztbyXB37x0rBhVV3nxBGGzIxxBu1xTswHa/8lJ2NQUf1zfp6XFuOEefxvo6yWOBSBXw/Bir5Rs8WEFJJltRpLKdQYDY7OO4SMMwhvo61TPo2+UymCHdxDayI9fIXTpzhcHwSVLO09CyS2d/OBRTSlhpqrAfbXfmpWkr9Eq3QnVMfnuPE4eZM/KTmAdD8XMj0cPRuXDJ3sEiCSeYzkJZgbyFPa79nGEqgP50ZzvzV8v4cM4kfwvhs9Ya7f2BIMgX2Th/blX47eER2w0FLjRjQ/h+NHjhj6MD7Y9+E2Ig5BfYhHFQAzEHA4AQltDRfB8FYhqa7ba1WZulOJjcO4s7JY=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: 0Nb/xF466KrOnvk9sM0Ot0pVN9JzvF0Gfu/2Al4pNoX9fbUIJ4kcYCDCC9g72LiFjk/YjyaO2ciGVwA5pyIE6lUkDMo9qbcMFVz5FevBiRykUGPoqyal2FCcXVpRVJMFEipqGC9jSYepXvOl1UapyXp9kQWYO6l2zKqbvTCtZKZEVNZ5D6NYF/J+MmRHL3jmyjRgf9dOlOhwY2GajNFgsjGNYu2gZ7BTA8TP+D/9r09QnVonvar3TSozqjDSkK2gAZI/DRJ9cqgelbo8XtGCqvc3iBU8kfMG6UKGrb+WFZyRxk+itfyOSd4Fos5yy+ZHmMHNXpGNZ33VTjz3nt67YwZrBtK7MjX1sUOdYhPO+LA6KoFXcmoUmyOZE1k7bJCFlbOtytSTFzTHD2wjsKuVLElzbJ7hBinQZTgxZxFYnKSsCkBsv3WY3HhYGIRpyMNEM0E4CH3+hoik8zBVBrv+0ipCyUgJmK1iOSDlPJHkibQGO6gDndgnxv7QmoWkMsOsta5Z8NXbC6dT3klJwnW4Na/slK+z4o1/aQMaAHvKip/CdUdu3gzd1Q1D96AmTh7DDKpIW/TIvkFrjU+Gk86D+vfXLISDm2yIjyR9IovoTkCg+o4IaOi5T12VRYjvFh+11LRQnY/pNNajbvRd25XgumZqd6tVCwNH7U4Ok4C2e3I=
